# NumPy Tutorial For Beginners

## What is NumPy ??

***
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
***

## Installing NumPy

python -m pip install --user numpy ✔ <br>
Different installaton processes https://scipy.org/install.html

`import numpy`

In [1]:
import numpy as np

## Why using NumPy when we have List?? 🤔

In [ ]:
a = [1, 2, 3]
b = [[1, 2, 3], [3, 4, 5]]

 1.Storage space 🎈

In [ ]:
import time
import sys

size = 10000

In [ ]:
our_list = range(size)
print(f"Size of list: {sys.getsizeof(1)* len(our_list)}")

In [ ]:
our_numpy_array = np.arange(size)
print(f"Size of NumPy array: {our_numpy_array.itemsize * our_numpy_array.size}")

2.Speed ⚡

In [ ]:
size = 10000000

list1 = range(size)
list2 = range(size)

In [ ]:
starting_time = time.time()

result = []
for i in range(0, len(list1)):
    result.append(list1[i] + list2[i])

print(f"Execution time for list addition: {(time.time()-starting_time) * 1000}")

In [ ]:
numpy_array_1 = np.arange(size)
numpy_array_2 = np.arange(size)

In [ ]:
starting_time = time.time()

result = numpy_array_1 + numpy_array_2

print(f"Execution time for NumPy array addition: {(time.time()-starting_time) * 1000}")

## Who is the winner ?? 💐🏆

## Lets start from Nothing 🧐

In [ ]:
e = np.empty(10)
e

In [ ]:
z = np.zeros(10)
print(z)

In [ ]:
type(z)

In [ ]:
z.ndim

In [ ]:
type(z[0])

In [ ]:
z.shape

In [ ]:
z.shape = (2, 5)
z

In [ ]:
o = np.ones(10)
o

What if we need some limited values in a range

In [ ]:
limited = np.linspace(1, 20, 5)
limited

## Now we have something 😇

In [ ]:
numpy_array = np.array([4, 5, 6, 7])
numpy_array

In [ ]:
values = range(5)
numpy_array = np.array(values)
numpy_array

In [ ]:
type(numpy_array)

In [ ]:
matrix = [[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 0]]
numpy_array = np.array(matrix)
numpy_array

In [ ]:
numpy_array.shape

In [ ]:
numpy_array.shape = (2, 6)
numpy_array

In [ ]:
a = np.arange(15).reshape(3, 5)
a

In [ ]:
a.ndim

In [ ]:
a.dtype

In [ ]:
a.itemsize

In [ ]:
a.size

## Complex Arithmatic ⚠

A complex number has two part, one is real and another is imaginary. <br> Complex Number is represented by
z = (x + yj)
where x is the real part and j = root(-1) mutiplied with y is the imaginary part.

In [ ]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

In [ ]:
d = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c + d)

In [ ]:
print(c * d)

In [ ]:
a = np.arange( 10, 30, 5 )
a

## Basic Operations and Linear Algebra 🛠

In [ ]:
A = np.array( [[5,2], [7,1]] )
B = np.array( [[2,0], [3,4]] )

In [ ]:
A.sum()

In [ ]:
A.min()

In [ ]:
A.max()

In [ ]:
A.sort()
A

In [ ]:
print(A)
A < 4

In [ ]:
np.exp(A)

In [ ]:
np.log(A)

In [ ]:
np.sin(A)

In [ ]:
np.transpose(A)

In [ ]:
np.sqrt(A)

In [ ]:
print(A.mean())
print(np.median(A))
print(np.std(A))

In [ ]:
A - B

In [ ]:
np.add(A, B)

In [ ]:
A * B

In [ ]:
np.multiply(A,B)

In [ ]:
A @ B

In [ ]:
A.dot(B)

## Random sampling [np.random]

In [ ]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
np.random.rand(3,2)

In [ ]:
r1 = np.random.randint(10)
r1

In [ ]:
np.random.seed(0)
# set of 6 values
r2 = np.random.randint(10, size=6)
r2

In [ ]:
r2 = np.random.ranf()
r2

In [ ]:
# Return a sample (or samples) from the “standard normal” distribution.
np.random.randn()

## Slicing 🔪

In [ ]:
x = np.array(range(10))
x

In [ ]:
x[0]

In [ ]:
x[-1]

In [ ]:
x[3:6]

In [ ]:
x[1:7:2]

## Spliting 🪓✂

In [ ]:
a = np.arange(30).reshape(5,6)
a

In [ ]:
np.hsplit(a, 3)

## Copy 🖨

In [2]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [3]:
c = a
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [4]:
c is a

True

In [5]:
# Shallow Copy
c = a.view()
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [6]:
c.base is a.base

True

In [7]:
c.flags.owndata

False

In [ ]:
# Deep Copy
c = a.copy()
c

In [ ]:
c.base is a.base

In [ ]:
c.flags.owndata

# References

- https://numpy.org/devdocs/reference/index.html
- https://www.kaggle.com/paraspatidar/numpy-tricks-from-zero-to-hero
- https://numpy.org/devdocs/user/quickstart.html
- https://scipy-lectures.org/

#                                                Thank You