# NumPy Tutorial For Beginners

## What is NumPy ??

***
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
***

## Installing NumPy

python -m pip install --user numpy ✔ <br>
Different installaton processes https://scipy.org/install.html

`import numpy`

In [1]:
import numpy as np

## Why using NumPy when we have List?? 🤔

In [2]:
a = [1, 2, 3]
b = [[1, 2, 3], [3, 4, 5]]

 1.Storage space 🎈

In [3]:
import time
import sys

size = 10000

In [4]:
our_list = range(size)
print(f"Size of list: {sys.getsizeof(1)* len(our_list)}")

Size of list: 280000


In [5]:
our_numpy_array = np.arange(size)
print(f"Size of NumPy array: {our_numpy_array.itemsize * our_numpy_array.size}")

Size of NumPy array: 40000


2.Speed ⚡

In [6]:
size = 10000000

list1 = range(size)
list2 = range(size)

In [7]:
starting_time = time.time()

result = []
for i in range(0, len(list1)):
    result.append(list1[i] + list2[i])

print(f"Execution time for list addition: {(time.time()-starting_time) * 1000}")

Execution time for list addition: 4571.812868118286


In [8]:
numpy_array_1 = np.arange(size)
numpy_array_2 = np.arange(size)

In [9]:
starting_time = time.time()

result = numpy_array_1 + numpy_array_2

print(f"Execution time for NumPy array addition: {(time.time()-starting_time) * 1000}")

Execution time for NumPy array addition: 217.95058250427246


## Who is the winner ?? 💐🏆

Ans:Numpy

## Lets start from Nothing 🧐

In [10]:
e = np.empty(10)
e

array([3.56043053e-307, 1.60219306e-306, 7.56571288e-307, 1.89146896e-307,
       1.37961302e-306, 1.05699242e-307, 8.01097889e-307, 1.33512308e-306,
       9.79103798e-307, 1.24610927e-306])

In [11]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
type(z)

numpy.ndarray

In [13]:
z.ndim

1

In [14]:
type(z[0])

numpy.float64

In [15]:
z.shape

(10,)

In [16]:
z.shape = (2, 5)
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
o = np.ones(10)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

What if we need some limited values in a range

In [18]:
limited = np.linspace(1, 20, 5)
limited

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

## Now we have something 😇

In [19]:
numpy_array = np.array([4, 5, 6, 7])
numpy_array

array([4, 5, 6, 7])

In [20]:
values = range(5)
numpy_array = np.array(values)
numpy_array

array([0, 1, 2, 3, 4])

In [21]:
type(numpy_array)

numpy.ndarray

In [22]:
matrix = [[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 0]]
numpy_array = np.array(matrix)
numpy_array

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 0]])

In [23]:
numpy_array.shape

(3, 4)

In [24]:
numpy_array.shape = (2, 6)
numpy_array

array([[1, 2, 3, 4, 4, 5],
       [6, 7, 7, 8, 9, 0]])

In [25]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
a.ndim

2

In [27]:
a.dtype

dtype('int32')

In [28]:
a.itemsize

4

In [29]:
a.size

15

## Complex Arithmatic ⚠

A complex number has two part, one is real and another is imaginary. <br> Complex Number is represented by
z = (x + yj)
where x is the real part and j = root(-1) mutiplied with y is the imaginary part.

In [30]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [31]:
d = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c + d)

[[2.+0.j 4.+0.j]
 [6.+0.j 8.+0.j]]


In [32]:
print(c * d)

[[ 1.+0.j  4.+0.j]
 [ 9.+0.j 16.+0.j]]


In [33]:
a = np.arange( 10, 30, 5 )
a

array([10, 15, 20, 25])

## Basic Operations and Linear Algebra 🛠

In [34]:
A = np.array( [[5,2], [7,1]] )
B = np.array( [[2,0], [3,4]] )

In [35]:
A.sum()

15

In [36]:
A.min()

1

In [37]:
A.max()

7

In [38]:
A.sort()
A

array([[2, 5],
       [1, 7]])

In [39]:
print(A)
A < 4

[[2 5]
 [1 7]]


array([[ True, False],
       [ True, False]])

In [40]:
np.exp(A)

array([[   7.3890561 ,  148.4131591 ],
       [   2.71828183, 1096.63315843]])

In [41]:
np.log(A)

array([[0.69314718, 1.60943791],
       [0.        , 1.94591015]])

In [42]:
np.sin(A)

array([[ 0.90929743, -0.95892427],
       [ 0.84147098,  0.6569866 ]])

In [43]:
np.transpose(A)

array([[2, 1],
       [5, 7]])

In [44]:
np.sqrt(A)

array([[1.41421356, 2.23606798],
       [1.        , 2.64575131]])

In [45]:
print(A.mean())
print(np.median(A))
print(np.std(A))

3.75
3.5
2.384848003542364


In [46]:
A - B

array([[ 0,  5],
       [-2,  3]])

In [47]:
np.add(A, B)

array([[ 4,  5],
       [ 4, 11]])

In [48]:
A * B

array([[ 4,  0],
       [ 3, 28]])

In [49]:
np.multiply(A,B)

array([[ 4,  0],
       [ 3, 28]])

In [50]:
A @ B

array([[19, 20],
       [23, 28]])

In [51]:
A.dot(B)

array([[19, 20],
       [23, 28]])

## Random sampling [np.random]

In [52]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
np.random.rand(3,2)

array([[0.69694882, 0.07725914],
       [0.20631872, 0.75645207],
       [0.4613177 , 0.4636184 ]])

In [53]:
r1 = np.random.randint(10)
r1

8

In [54]:
np.random.seed(0)
# set of 6 values
r2 = np.random.randint(10, size=6)
r2

array([5, 0, 3, 3, 7, 9])

In [55]:
r2 = np.random.ranf()
r2

0.6235636967859723

In [56]:
# Return a sample (or samples) from the “standard normal” distribution.
np.random.randn()

-1.5169827345248437

## Slicing 🔪

In [57]:
x = np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x[0]

0

In [59]:
x[-1]

9

In [60]:
x[3:6]

array([3, 4, 5])

In [61]:
x[1:7:2]

array([1, 3, 5])

## Spliting 🪓✂

In [62]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [63]:
np.hsplit(a, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

## Copy 🖨

In [64]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [65]:
c = a
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [66]:
c is a

True

In [67]:
# Shallow Copy
c = a.view()
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [68]:
c.base is a.base

True

In [69]:
c.flags.owndata

False

In [70]:
# Deep Copy
c = a.copy()
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [71]:
c.base is a.base

False

In [72]:
c.flags.owndata

True

# References

- https://numpy.org/devdocs/reference/index.html
- https://www.kaggle.com/paraspatidar/numpy-tricks-from-zero-to-hero
- https://numpy.org/devdocs/user/quickstart.html
- https://scipy-lectures.org/

<h3> <center> Thank You </center> </h3>

<h5><center>A JuputerNotebook for NumPy Tutorial by DeepScript</center></h5> 